### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by DerBeutlin** [mykter/TagTime-desktop#152]
As far as I understood is there is no possibility to have the exact same pings as the original TagTime implementation, even if one sets the seed to 666 and the start time to 07/10/2007 04:00 PM.
This makes it impossible to merge the tags with tags from the android implementation. Is there any implementation issues with providing this backwards compatibility?

**Comment by mykter** [comment]
Hi, there's no problem importing pings from another implementation, as long as you configure the mean period to be the same (the default is 45 mins). The app doesn't try and enforce that old pings match the current schedule, and your stats won't get messed up.

However, I think it does make sense to make the scheduler the same as original TagTime, to avoid any complications that arise. A PR would be welcome :wink:, otherwise I'll use this issue to change it round at some point.

**Comment by DerBeutlin** [comment]
I have no prior experience with Typescript but nonetheless I will try it out.
However, I have some difficulties getting the environment to run. I let the travis.yaml guide me to install
- node_js (tried out version 8 and 10)
- rpm
- xvfb

Using node_js 10 I can execute `npm install` sucessfully but then in `npm run build` I get
```
> tagtime-desktop@0.8.0 build /home/max/git/TagTime-desktop
> gulp clean:build && gulp build:tests

gulp[26034]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x90af00 node::Abort() [gulp]
 2: 0x90afd5  [gulp]
 3: 0x93f4fe node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb8becf  [gulp]
 5: 0xb8deda v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x31ebda6cfb5d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! tagtime-desktop@0.8.0 build: `gulp clean:build && gulp build:tests`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the tagtime-desktop@0.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
whereas using node_js version 8 I get
```
> electron@1.8.4 postinstall /home/max/git/TagTime-desktop/node_modules/electron
> node install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'electron-download'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/max/git/TagTime-desktop/node_modules/electron/install.js:9:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
when running `npm install`.
I'm using Ubuntu 18.04. Do you have any advice for me to get this running?

**Comment by mykter** [comment]
Thanks Max. Looks like npm bit-rot has set in. I'll try and take a look this weekend and bring it back to life with current versions.

**Comment by mykter** [comment]
@DerBeutlin ok all dependencies updated and the various node issues fixed. The AppVeyor build passes now (travis seems to have lost contact with the repo), so hopefully the build should work again.

You can just run `gulp` to have it monitor the project for changes and rebuild automatically.
